version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_docker
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html
    networks:
      - laravel_network

  webserver:
    image: nginx:latest
    container_name: nginx_web
    depends_on:
      - app
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    networks:
      - laravel_network

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: "mike"
      MYSQL_PASSWORD: "mike"
      MYSQL_ROOT_PASSWORD: "aaaa" 
    ports:
      - "3307:3306"  
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - laravel_network
  
networks:
  laravel_network:
    driver: bridge

volumes:
  dbdata:
    driver: local
